module.exports = {
  messages: {
    error: {
      UNAUTHORIZED: 'You need to sign in to access this feature.',
      INVALID_CLASS: 'The class sent is invalid.',
      INVALID_RACE: 'The race sent is invalid.',
      INVALID_GENDER: 'The gender sent is invalid.',
      INVALID_ATTRIBUTES: 'The attributes sent are invalid.',
      INVALID_ID: 'The id sent is invalid.',
      UNIQUE_CONSTRAINT: 'Data sent is violating a unique constraint.',
      INVALID_JSON: 'Data sent is an invalid json.',
      DOCUMENT_NOT_FOUND: 'No data found.',
      UNEXPECTED_RUNNING:
        'An unexpected error occurred while processing your request.',
    },
  },
  error: {
    name: {
      DOCUMENT_NOT_FOUND_ERROR: 'DocumentNotFoundError',
      VALIDATION_ERROR: 'ValidationError',
      NOT_FOUND: 'NotFoundError',
      INVALID_AUTH: 'InvalidAuthError',
      INVALID_SESSION: 'InvalidSessionError',
      INVALID_CLASS: 'InvalidClass',
      INVALID_RACE: 'InvalidRace',
      INVALID_GENDER: 'InvalidGender',
      INVALID_ATTRIBUTES: 'InvalidAttributes',
      INVALID_ID: 'InvalidId',
    },
    code: {
      UNIQUE_CONSTRAINT: 11000,
    },
    type: {
      PARSING_FAILED: 'entity.parse.failed',
    },
  },
  values: {
    cryptography: {
      PASSWORD_KEY: process.env.PASSWORD_KEY,
      TOKEN_KEY: process.env.TOKEN_KEY,
      SESSION_SIGNATURE_KEY: process.env.SESSION_SIGNATURE_KEY,
    },
    cookies: {
      SESSION: 'session',
    },
    STARTING_ATTRIBUTE_POINTS: 9,
    MAXIMUM_NAME_LENGTH: 26,
    CLASSES: ['Swordsman', 'Mage', 'Thief'],
    RACES: ['Human', 'Lizard', 'Undead', 'Dwarf', 'Elf'],
    GENDERS: ['Male', 'Female'],
    ATTRIBUTES: [
      'strength',
      'intelligence',
      'agility',
      'dexterity',
      'vitality',
    ],
    STARTING_MAP_ID: '5e88c755fca71f706874657e',
    STARTING_MAP_POSITION: {
      x: 0,
      y: 0,
    },
    DEFAULT_SIGHT_RANGE: 6,
    DEFAULT_ATTACK_RANGE: 1,
    STRENGTH_MULTIPLIER_TO_ATTACK: 1.15,
    DEXTERITY_MULTIPLIER_TO_ATTACK: 0.15,
    INTELLIGENCE_MULTIPLIER_TO_MAGIC_ATTACK: 0.95,
    VITALITY_MULTIPLIER_TO_DEFENSE: 0.75,
    VITALITY_MULTIPLIER_TO_MAGIC_DEFENSE: 0.25,
    INTELLIGENCE_MULTIPLIER_TO_MAGIC_DEFENSE: 0.55,
    DEXTERITY_MULTIPLIER_TO_HIT: 0.75,
    AGILITY_MULTIPLIER_TO_FLEE: 0.5,
    VITALITY_INCREMENT_TO_HEALTH: 14,
    INTELLIGENCE_INCREMENT_TO_MANA: 7,
  },
  endpoints: {
    CREATE_ADVENTURER: '/',
    RETRIEVE_ADVENTURERS: '/',
    RETRIEVE_ADVENTURER: '/:id',
    RETRIEVE_SELECTED_ADVENTURER: '/selected',
    SELECT_ADVENTURER: '/select',
    RETRIEVE_ITEMS: '/',
    RETRIEVE_ITEM: '/:id',
  },
  tables: {
    USERS: 'Users',
    ADVENTURERS: 'Adventurers',
    ITEMS: 'Items',
  },
  selections: {
    USER_WITH_ONLY_ID_DATA: ['_id'],
    USER_WITH_PROFILE_DATA: ['_id', 'email', 'selectedAdventurer'],
    USER_WITH_PASSWORD_DATA: ['_id', 'password'],
    ADVENTURER_WITH_SUMMARY_DATE: [
      '_id',
      'name',
      'level',
      'class',
      'race',
      'gender',
    ],
  },
  item: {
    TYPES: ['miscellaneous', 'equipment', 'consumable', 'card'],
    MISCELLANEOUS_TYPE: 'miscellaneous',
    EQUIPMENT_TYPE: 'equipment',
    CONSUMABLE_TYPE: 'consumable',
    CARD_TYPE: 'card',
  },
};
